// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemperatureData;

#nullable disable

namespace TemperatureData.Migrations
{
    [DbContext(typeof(TemperatureContext))]
    [Migration("20231004233447_addsensordefaults")]
    partial class addsensordefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TemperatureDomain.SensorLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cold")
                        .HasColumnType("float");

                    b.Property<double>("Hot")
                        .HasColumnType("float");

                    b.Property<double>("Warm")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("SensorLimits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cold = 22.0,
                            Hot = 35.0,
                            Warm = 0.0
                        });
                });

            modelBuilder.Entity("TemperatureDomain.TemperatureRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TemperatureRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
